DotnetApp/Controllers/GradeController.cs
using System;
using ClientNotifications;
using DotnetApp.Models;
using DotnetApp.Repository.Interface;
using DotnetApp.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using static ClientNotifications.Helpers.NotificationHelper;

namespace DotnetApp.Controllers
{
    public class GradeController : Controller
    {
        private IGradeRepository _gradeRepository;
        private IGradeService _gradeService;
        private IClientNotification _clientNotification;

        public GradeController(IGradeRepository gradeRepository,
                                IGradeService gradeService,
                                IClientNotification clientNotification)
        {
            _gradeRepository = gradeRepository;
            _gradeService = gradeService;
            _clientNotification = clientNotification;

        }

        public ActionResult Index()
        {
            var grades = _gradeRepository.GetAllGrades();
            return View(grades);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            try
            {
                var single_grade = _gradeService.GetById(id);
                return View(single_grade);
            }
            catch (Exception e)
            {
                _clientNotification.AddSweetNotification("Error", e.Message.ToString(), NotificationType.error);
                return RedirectToAction(nameof(Index));
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Grade grade)
        {
            try
            {
                _gradeService.Create(grade);
                _clientNotification.AddSweetNotification("Success", "Grade Successfully Created.", NotificationType.success);
            }
            catch (Exception e)
            {
                _clientNotification.AddSweetNotification("Error", e.Message.ToString(), NotificationType.error);
                return View();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            try
            {
                var single_grade = _gradeService.GetById(id);
                return View(single_grade);
            }
            catch (Exception e)
            {
                _clientNotification.AddSweetNotification("Error", e.Message.ToString(), NotificationType.error);
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public ActionResult Edit(Grade grade)
        {
            try
            {
                _gradeService.Update(grade);
                _clientNotification.AddSweetNotification("Success", "Grade Successfully Updated.", NotificationType.success);

            }
            catch (Exception e)
            {
                _clientNotification.AddSweetNotification("Error", e.Message.ToString(), NotificationType.error);
                return View();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Delete(Grade grade)
        {
            try
            {
                _gradeService.Delete(grade);
                _clientNotification.AddSweetNotification("Success", "Grade Successfully Deleted.", NotificationType.success);
            }
            catch (Exception e)
            {
                _clientNotification.AddSweetNotification("Error", e.Message.ToString(), NotificationType.error);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

DotnetApp/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using ClientNotifications;
using DotnetApp.Models;
using DotnetApp.Repository.Interface;
using DotnetApp.Services.Interface;
using DotnetApp.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static ClientNotifications.Helpers.NotificationHelper;

namespace DotnetApp.Controllers
{
    public class StudentController : Controller
    {
        private IStudentRepository _studentRepository;
        private IGradeRepository _gradeRepository;
        private IStudentService _studentService;
        private IClientNotification _clientNotification;

        public StudentController(IStudentRepository studentRepository,
                                IGradeRepository gradeRepository,
                                IStudentService studentService,
                                 IClientNotification clientNotification)
        {
            _studentRepository = studentRepository;
            _gradeRepository = gradeRepository;
            _studentService = studentService;
            _clientNotification = clientNotification;
        }

        public IActionResult Index()
        {
            var students = _studentRepository.GetAllStudents();
            return View(students);
        }

        public IActionResult Create()
        {
            var grades = new List<Grade>();
            grades.AddRange(_gradeRepository.GetAllGrades());
            ViewBag.grades = new SelectList(grades, "grade_id", "grade_name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Student student)

        {
            try
            {
                _studentService.Create(student);
                _clientNotification.AddSweetNotification("Success","Student Successfully Created.", NotificationType.success);
            }
            catch (Exception e)
            {
                _clientNotification.AddSweetNotification("Error",e.Message.ToString(), NotificationType.error);
                return View();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            try
            {
                var single_student = _studentService.GetById(id);
                return View(single_student);
            }
            catch (Exception e)
            {
                _clientNotification.AddSweetNotification("Error", e.Message.ToString(), NotificationType.error);
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            try
            {
                var single_student = _studentService.GetById(id);
                return View(single_student);
            }
            catch (Exception e)
            {
                _clientNotification.AddSweetNotification("Error", e.Message.ToString(), NotificationType.error);
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public IActionResult Edit(Student student)
        {
            try
            {
                _studentService.Update(student);
                _clientNotification.AddSweetNotification("Success", "Student Successfully Updated.", NotificationType.success);

            }
            catch (Exception e)
            {
                _clientNotification.AddSweetNotification("Error", e.Message.ToString(), NotificationType.error);
                return View();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Delete(Student student)
        {
            try
            {
                _studentService.Delete(student);
                _clientNotification.AddSweetNotification("Success", "Student Successfully Deleted.", NotificationType.success);
            }
            catch (Exception e)
            {
                _clientNotification.AddSweetNotification("Error", e.Message.ToString(), NotificationType.error);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

DotnetApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DotnetApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/vendor/toastr/build/toastr.css" />
        <link rel="stylesheet" href="~/vendor/bootstrap-sweetalert/dist/sweetalert.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/vendor/toastr/build/toastr.css" />
        <link rel="stylesheet" href="~/vendor/bootstrap-sweetalert/dist/sweetalert.css" />
    </environment>
</head>
<body>
    @await Component.InvokeAsync("ClientNotifications.Notify")

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DotnetApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Student" asp-action="Index">Student</a></li>
                    <li><a asp-area="" asp-controller="Grade" asp-action="Index">Grade</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - DotnetApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/vendor/toastr/build/toastr.min.js" asp-append-version="true"></script>
        <script src="~/vendor/bootstrap-sweetalert/dist/sweetalert.min.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/vendor/toastr/build/toastr.min.js" asp-append-version="true"></script>
        <script src="~/vendor/bootstrap-sweetalert/dist/sweetalert.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>